// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: delegate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delegate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScoreSheetId  int32                  `protobuf:"varint,2,opt,name=score_sheet_id,json=scoreSheetId,proto3" json:"score_sheet_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delegate) Reset() {
	*x = Delegate{}
	mi := &file_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delegate) ProtoMessage() {}

func (x *Delegate) ProtoReflect() protoreflect.Message {
	mi := &file_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delegate.ProtoReflect.Descriptor instead.
func (*Delegate) Descriptor() ([]byte, []int) {
	return file_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *Delegate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Delegate) GetScoreSheetId() int32 {
	if x != nil {
		return x.ScoreSheetId
	}
	return 0
}

func (x *Delegate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_delegate_proto protoreflect.FileDescriptor

const file_delegate_proto_rawDesc = "" +
	"\n" +
	"\x0edelegate.proto\x12\x02pb\"T\n" +
	"\bDelegate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12$\n" +
	"\x0escore_sheet_id\x18\x02 \x01(\x05R\fscoreSheetId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_delegate_proto_rawDescOnce sync.Once
	file_delegate_proto_rawDescData []byte
)

func file_delegate_proto_rawDescGZIP() []byte {
	file_delegate_proto_rawDescOnce.Do(func() {
		file_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delegate_proto_rawDesc), len(file_delegate_proto_rawDesc)))
	})
	return file_delegate_proto_rawDescData
}

var file_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_delegate_proto_goTypes = []any{
	(*Delegate)(nil), // 0: pb.Delegate
}
var file_delegate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_delegate_proto_init() }
func file_delegate_proto_init() {
	if File_delegate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delegate_proto_rawDesc), len(file_delegate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delegate_proto_goTypes,
		DependencyIndexes: file_delegate_proto_depIdxs,
		MessageInfos:      file_delegate_proto_msgTypes,
	}.Build()
	File_delegate_proto = out.File
	file_delegate_proto_goTypes = nil
	file_delegate_proto_depIdxs = nil
}
