// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: parameter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parameter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScoreSheetId       int32                  `protobuf:"varint,2,opt,name=score_sheet_id,json=scoreSheetId,proto3" json:"score_sheet_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RuleType           string                 `protobuf:"bytes,4,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	IsSpecialParameter bool                   `protobuf:"varint,5,opt,name=is_special_parameter,json=isSpecialParameter,proto3" json:"is_special_parameter,omitempty"`
	SpecialScoresRule  string                 `protobuf:"bytes,6,opt,name=special_scores_rule,json=specialScoresRule,proto3" json:"special_scores_rule,omitempty"`
	SpecialLengthRule  string                 `protobuf:"bytes,7,opt,name=special_length_rule,json=specialLengthRule,proto3" json:"special_length_rule,omitempty"`
	ScoreWeight        float64                `protobuf:"fixed64,8,opt,name=score_weight,json=scoreWeight,proto3" json:"score_weight,omitempty"`
	LengthWeight       float64                `protobuf:"fixed64,9,opt,name=length_weight,json=lengthWeight,proto3" json:"length_weight,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_parameter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_parameter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_parameter_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Parameter) GetScoreSheetId() int32 {
	if x != nil {
		return x.ScoreSheetId
	}
	return 0
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *Parameter) GetIsSpecialParameter() bool {
	if x != nil {
		return x.IsSpecialParameter
	}
	return false
}

func (x *Parameter) GetSpecialScoresRule() string {
	if x != nil {
		return x.SpecialScoresRule
	}
	return ""
}

func (x *Parameter) GetSpecialLengthRule() string {
	if x != nil {
		return x.SpecialLengthRule
	}
	return ""
}

func (x *Parameter) GetScoreWeight() float64 {
	if x != nil {
		return x.ScoreWeight
	}
	return 0
}

func (x *Parameter) GetLengthWeight() float64 {
	if x != nil {
		return x.LengthWeight
	}
	return 0
}

var File_parameter_proto protoreflect.FileDescriptor

const file_parameter_proto_rawDesc = "" +
	"\n" +
	"\x0fparameter.proto\x12\x02pb\"\xcc\x02\n" +
	"\tParameter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12$\n" +
	"\x0escore_sheet_id\x18\x02 \x01(\x05R\fscoreSheetId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\trule_type\x18\x04 \x01(\tR\bruleType\x120\n" +
	"\x14is_special_parameter\x18\x05 \x01(\bR\x12isSpecialParameter\x12.\n" +
	"\x13special_scores_rule\x18\x06 \x01(\tR\x11specialScoresRule\x12.\n" +
	"\x13special_length_rule\x18\a \x01(\tR\x11specialLengthRule\x12!\n" +
	"\fscore_weight\x18\b \x01(\x01R\vscoreWeight\x12#\n" +
	"\rlength_weight\x18\t \x01(\x01R\flengthWeightB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_parameter_proto_rawDescOnce sync.Once
	file_parameter_proto_rawDescData []byte
)

func file_parameter_proto_rawDescGZIP() []byte {
	file_parameter_proto_rawDescOnce.Do(func() {
		file_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parameter_proto_rawDesc), len(file_parameter_proto_rawDesc)))
	})
	return file_parameter_proto_rawDescData
}

var file_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameter_proto_goTypes = []any{
	(*Parameter)(nil), // 0: pb.Parameter
}
var file_parameter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parameter_proto_init() }
func file_parameter_proto_init() {
	if File_parameter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parameter_proto_rawDesc), len(file_parameter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameter_proto_goTypes,
		DependencyIndexes: file_parameter_proto_depIdxs,
		MessageInfos:      file_parameter_proto_msgTypes,
	}.Build()
	File_parameter_proto = out.File
	file_parameter_proto_goTypes = nil
	file_parameter_proto_depIdxs = nil
}
