// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_delete_score.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreId       int32                  `protobuf:"varint,1,opt,name=score_id,json=scoreId,proto3" json:"score_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScoreRequest) Reset() {
	*x = DeleteScoreRequest{}
	mi := &file_rpc_delete_score_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoreRequest) ProtoMessage() {}

func (x *DeleteScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_score_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteScoreRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_score_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteScoreRequest) GetScoreId() int32 {
	if x != nil {
		return x.ScoreId
	}
	return 0
}

type DeleteScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScoreResponse) Reset() {
	*x = DeleteScoreResponse{}
	mi := &file_rpc_delete_score_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoreResponse) ProtoMessage() {}

func (x *DeleteScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_score_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteScoreResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_score_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_delete_score_proto protoreflect.FileDescriptor

const file_rpc_delete_score_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_delete_score.proto\x12\x02pb\"/\n" +
	"\x12DeleteScoreRequest\x12\x19\n" +
	"\bscore_id\x18\x01 \x01(\x05R\ascoreId\"/\n" +
	"\x13DeleteScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_rpc_delete_score_proto_rawDescOnce sync.Once
	file_rpc_delete_score_proto_rawDescData []byte
)

func file_rpc_delete_score_proto_rawDescGZIP() []byte {
	file_rpc_delete_score_proto_rawDescOnce.Do(func() {
		file_rpc_delete_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_score_proto_rawDesc), len(file_rpc_delete_score_proto_rawDesc)))
	})
	return file_rpc_delete_score_proto_rawDescData
}

var file_rpc_delete_score_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_score_proto_goTypes = []any{
	(*DeleteScoreRequest)(nil),  // 0: pb.DeleteScoreRequest
	(*DeleteScoreResponse)(nil), // 1: pb.DeleteScoreResponse
}
var file_rpc_delete_score_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_score_proto_init() }
func file_rpc_delete_score_proto_init() {
	if File_rpc_delete_score_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_score_proto_rawDesc), len(file_rpc_delete_score_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_score_proto_goTypes,
		DependencyIndexes: file_rpc_delete_score_proto_depIdxs,
		MessageInfos:      file_rpc_delete_score_proto_msgTypes,
	}.Build()
	File_rpc_delete_score_proto = out.File
	file_rpc_delete_score_proto_goTypes = nil
	file_rpc_delete_score_proto_depIdxs = nil
}
