// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_get_feedback_by_llm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedbackByLLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delegates     []*DelegateInput       `protobuf:"bytes,2,rep,name=delegates,proto3" json:"delegates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByLLMRequest) Reset() {
	*x = GetFeedbackByLLMRequest{}
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByLLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByLLMRequest) ProtoMessage() {}

func (x *GetFeedbackByLLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByLLMRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackByLLMRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_feedback_by_llm_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedbackByLLMRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFeedbackByLLMRequest) GetDelegates() []*DelegateInput {
	if x != nil {
		return x.Delegates
	}
	return nil
}

type DelegateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelegateName  string                 `protobuf:"bytes,1,opt,name=delegate_name,json=delegateName,proto3" json:"delegate_name,omitempty"`
	Parameters    []*ParameterInput      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateInput) Reset() {
	*x = DelegateInput{}
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateInput) ProtoMessage() {}

func (x *DelegateInput) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateInput.ProtoReflect.Descriptor instead.
func (*DelegateInput) Descriptor() ([]byte, []int) {
	return file_rpc_get_feedback_by_llm_proto_rawDescGZIP(), []int{1}
}

func (x *DelegateInput) GetDelegateName() string {
	if x != nil {
		return x.DelegateName
	}
	return ""
}

func (x *DelegateInput) GetParameters() []*ParameterInput {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ParameterInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterName string                 `protobuf:"bytes,1,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	Received      float64                `protobuf:"fixed64,2,opt,name=received,proto3" json:"received,omitempty"`
	Highest       float64                `protobuf:"fixed64,3,opt,name=highest,proto3" json:"highest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterInput) Reset() {
	*x = ParameterInput{}
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterInput) ProtoMessage() {}

func (x *ParameterInput) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterInput.ProtoReflect.Descriptor instead.
func (*ParameterInput) Descriptor() ([]byte, []int) {
	return file_rpc_get_feedback_by_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ParameterInput) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

func (x *ParameterInput) GetReceived() float64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *ParameterInput) GetHighest() float64 {
	if x != nil {
		return x.Highest
	}
	return 0
}

type DelegateFeedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelegateName  string                 `protobuf:"bytes,1,opt,name=delegate_name,json=delegateName,proto3" json:"delegate_name,omitempty"`
	FeedbackText  string                 `protobuf:"bytes,2,opt,name=feedback_text,json=feedbackText,proto3" json:"feedback_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateFeedback) Reset() {
	*x = DelegateFeedback{}
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateFeedback) ProtoMessage() {}

func (x *DelegateFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateFeedback.ProtoReflect.Descriptor instead.
func (*DelegateFeedback) Descriptor() ([]byte, []int) {
	return file_rpc_get_feedback_by_llm_proto_rawDescGZIP(), []int{3}
}

func (x *DelegateFeedback) GetDelegateName() string {
	if x != nil {
		return x.DelegateName
	}
	return ""
}

func (x *DelegateFeedback) GetFeedbackText() string {
	if x != nil {
		return x.FeedbackText
	}
	return ""
}

type GetFeedbackByLLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedbacks     []*DelegateFeedback    `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByLLMResponse) Reset() {
	*x = GetFeedbackByLLMResponse{}
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByLLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByLLMResponse) ProtoMessage() {}

func (x *GetFeedbackByLLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_feedback_by_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByLLMResponse.ProtoReflect.Descriptor instead.
func (*GetFeedbackByLLMResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_feedback_by_llm_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedbackByLLMResponse) GetFeedbacks() []*DelegateFeedback {
	if x != nil {
		return x.Feedbacks
	}
	return nil
}

var File_rpc_get_feedback_by_llm_proto protoreflect.FileDescriptor

const file_rpc_get_feedback_by_llm_proto_rawDesc = "" +
	"\n" +
	"\x1drpc_get_feedback_by_llm.proto\x12\x02pb\"c\n" +
	"\x17GetFeedbackByLLMRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12/\n" +
	"\tdelegates\x18\x02 \x03(\v2\x11.pb.DelegateInputR\tdelegates\"h\n" +
	"\rDelegateInput\x12#\n" +
	"\rdelegate_name\x18\x01 \x01(\tR\fdelegateName\x122\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x12.pb.ParameterInputR\n" +
	"parameters\"m\n" +
	"\x0eParameterInput\x12%\n" +
	"\x0eparameter_name\x18\x01 \x01(\tR\rparameterName\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\x01R\breceived\x12\x18\n" +
	"\ahighest\x18\x03 \x01(\x01R\ahighest\"\\\n" +
	"\x10DelegateFeedback\x12#\n" +
	"\rdelegate_name\x18\x01 \x01(\tR\fdelegateName\x12#\n" +
	"\rfeedback_text\x18\x02 \x01(\tR\ffeedbackText\"N\n" +
	"\x18GetFeedbackByLLMResponse\x122\n" +
	"\tfeedbacks\x18\x01 \x03(\v2\x14.pb.DelegateFeedbackR\tfeedbacksB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_get_feedback_by_llm_proto_rawDescOnce sync.Once
	file_rpc_get_feedback_by_llm_proto_rawDescData []byte
)

func file_rpc_get_feedback_by_llm_proto_rawDescGZIP() []byte {
	file_rpc_get_feedback_by_llm_proto_rawDescOnce.Do(func() {
		file_rpc_get_feedback_by_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_feedback_by_llm_proto_rawDesc), len(file_rpc_get_feedback_by_llm_proto_rawDesc)))
	})
	return file_rpc_get_feedback_by_llm_proto_rawDescData
}

var file_rpc_get_feedback_by_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_get_feedback_by_llm_proto_goTypes = []any{
	(*GetFeedbackByLLMRequest)(nil),  // 0: pb.GetFeedbackByLLMRequest
	(*DelegateInput)(nil),            // 1: pb.DelegateInput
	(*ParameterInput)(nil),           // 2: pb.ParameterInput
	(*DelegateFeedback)(nil),         // 3: pb.DelegateFeedback
	(*GetFeedbackByLLMResponse)(nil), // 4: pb.GetFeedbackByLLMResponse
}
var file_rpc_get_feedback_by_llm_proto_depIdxs = []int32{
	1, // 0: pb.GetFeedbackByLLMRequest.delegates:type_name -> pb.DelegateInput
	2, // 1: pb.DelegateInput.parameters:type_name -> pb.ParameterInput
	3, // 2: pb.GetFeedbackByLLMResponse.feedbacks:type_name -> pb.DelegateFeedback
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_get_feedback_by_llm_proto_init() }
func file_rpc_get_feedback_by_llm_proto_init() {
	if File_rpc_get_feedback_by_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_feedback_by_llm_proto_rawDesc), len(file_rpc_get_feedback_by_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_feedback_by_llm_proto_goTypes,
		DependencyIndexes: file_rpc_get_feedback_by_llm_proto_depIdxs,
		MessageInfos:      file_rpc_get_feedback_by_llm_proto_msgTypes,
	}.Build()
	File_rpc_get_feedback_by_llm_proto = out.File
	file_rpc_get_feedback_by_llm_proto_goTypes = nil
	file_rpc_get_feedback_by_llm_proto_depIdxs = nil
}
