// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_update_score_sheet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateScoreSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheetId  int32                  `protobuf:"varint,1,opt,name=score_sheet_id,json=scoreSheetId,proto3" json:"score_sheet_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	CommitteeName *string                `protobuf:"bytes,3,opt,name=committee_name,json=committeeName,proto3,oneof" json:"committee_name,omitempty"`
	Chair         *string                `protobuf:"bytes,4,opt,name=chair,proto3,oneof" json:"chair,omitempty"`
	ViceChair     *string                `protobuf:"bytes,5,opt,name=vice_chair,json=viceChair,proto3,oneof" json:"vice_chair,omitempty"`
	Rapporteur    *string                `protobuf:"bytes,6,opt,name=rapporteur,proto3,oneof" json:"rapporteur,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreSheetRequest) Reset() {
	*x = UpdateScoreSheetRequest{}
	mi := &file_rpc_update_score_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreSheetRequest) ProtoMessage() {}

func (x *UpdateScoreSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_score_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreSheetRequest.ProtoReflect.Descriptor instead.
func (*UpdateScoreSheetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_score_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateScoreSheetRequest) GetScoreSheetId() int32 {
	if x != nil {
		return x.ScoreSheetId
	}
	return 0
}

func (x *UpdateScoreSheetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateScoreSheetRequest) GetCommitteeName() string {
	if x != nil && x.CommitteeName != nil {
		return *x.CommitteeName
	}
	return ""
}

func (x *UpdateScoreSheetRequest) GetChair() string {
	if x != nil && x.Chair != nil {
		return *x.Chair
	}
	return ""
}

func (x *UpdateScoreSheetRequest) GetViceChair() string {
	if x != nil && x.ViceChair != nil {
		return *x.ViceChair
	}
	return ""
}

func (x *UpdateScoreSheetRequest) GetRapporteur() string {
	if x != nil && x.Rapporteur != nil {
		return *x.Rapporteur
	}
	return ""
}

type UpdateScoreSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheet    *ScoreSheet            `protobuf:"bytes,1,opt,name=score_sheet,json=scoreSheet,proto3" json:"score_sheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreSheetResponse) Reset() {
	*x = UpdateScoreSheetResponse{}
	mi := &file_rpc_update_score_sheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreSheetResponse) ProtoMessage() {}

func (x *UpdateScoreSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_score_sheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreSheetResponse.ProtoReflect.Descriptor instead.
func (*UpdateScoreSheetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_score_sheet_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateScoreSheetResponse) GetScoreSheet() *ScoreSheet {
	if x != nil {
		return x.ScoreSheet
	}
	return nil
}

var File_rpc_update_score_sheet_proto protoreflect.FileDescriptor

const file_rpc_update_score_sheet_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_update_score_sheet.proto\x12\x02pb\x1a\x11score_sheet.proto\"\xac\x02\n" +
	"\x17UpdateScoreSheetRequest\x12$\n" +
	"\x0escore_sheet_id\x18\x01 \x01(\x05R\fscoreSheetId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12*\n" +
	"\x0ecommittee_name\x18\x03 \x01(\tH\x01R\rcommitteeName\x88\x01\x01\x12\x19\n" +
	"\x05chair\x18\x04 \x01(\tH\x02R\x05chair\x88\x01\x01\x12\"\n" +
	"\n" +
	"vice_chair\x18\x05 \x01(\tH\x03R\tviceChair\x88\x01\x01\x12#\n" +
	"\n" +
	"rapporteur\x18\x06 \x01(\tH\x04R\n" +
	"rapporteur\x88\x01\x01B\a\n" +
	"\x05_nameB\x11\n" +
	"\x0f_committee_nameB\b\n" +
	"\x06_chairB\r\n" +
	"\v_vice_chairB\r\n" +
	"\v_rapporteur\"K\n" +
	"\x18UpdateScoreSheetResponse\x12/\n" +
	"\vscore_sheet\x18\x01 \x01(\v2\x0e.pb.ScoreSheetR\n" +
	"scoreSheetB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_rpc_update_score_sheet_proto_rawDescOnce sync.Once
	file_rpc_update_score_sheet_proto_rawDescData []byte
)

func file_rpc_update_score_sheet_proto_rawDescGZIP() []byte {
	file_rpc_update_score_sheet_proto_rawDescOnce.Do(func() {
		file_rpc_update_score_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_score_sheet_proto_rawDesc), len(file_rpc_update_score_sheet_proto_rawDesc)))
	})
	return file_rpc_update_score_sheet_proto_rawDescData
}

var file_rpc_update_score_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_score_sheet_proto_goTypes = []any{
	(*UpdateScoreSheetRequest)(nil),  // 0: pb.UpdateScoreSheetRequest
	(*UpdateScoreSheetResponse)(nil), // 1: pb.UpdateScoreSheetResponse
	(*ScoreSheet)(nil),               // 2: pb.ScoreSheet
}
var file_rpc_update_score_sheet_proto_depIdxs = []int32{
	2, // 0: pb.UpdateScoreSheetResponse.score_sheet:type_name -> pb.ScoreSheet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_score_sheet_proto_init() }
func file_rpc_update_score_sheet_proto_init() {
	if File_rpc_update_score_sheet_proto != nil {
		return
	}
	file_score_sheet_proto_init()
	file_rpc_update_score_sheet_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_score_sheet_proto_rawDesc), len(file_rpc_update_score_sheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_score_sheet_proto_goTypes,
		DependencyIndexes: file_rpc_update_score_sheet_proto_depIdxs,
		MessageInfos:      file_rpc_update_score_sheet_proto_msgTypes,
	}.Build()
	File_rpc_update_score_sheet_proto = out.File
	file_rpc_update_score_sheet_proto_goTypes = nil
	file_rpc_update_score_sheet_proto_depIdxs = nil
}
