// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_get_score_sheet_details.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScoreSheetDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheetId  int32                  `protobuf:"varint,1,opt,name=score_sheet_id,json=scoreSheetId,proto3" json:"score_sheet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreSheetDetailsRequest) Reset() {
	*x = GetScoreSheetDetailsRequest{}
	mi := &file_rpc_get_score_sheet_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreSheetDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreSheetDetailsRequest) ProtoMessage() {}

func (x *GetScoreSheetDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_score_sheet_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreSheetDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetScoreSheetDetailsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_score_sheet_details_proto_rawDescGZIP(), []int{0}
}

func (x *GetScoreSheetDetailsRequest) GetScoreSheetId() int32 {
	if x != nil {
		return x.ScoreSheetId
	}
	return 0
}

type GetScoreSheetDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheet    *ScoreSheet            `protobuf:"bytes,1,opt,name=score_sheet,json=scoreSheet,proto3" json:"score_sheet,omitempty"`
	Delegates     []*Delegate            `protobuf:"bytes,2,rep,name=delegates,proto3" json:"delegates,omitempty"`
	Parameters    []*Parameter           `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Scores        []*Score               `protobuf:"bytes,4,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreSheetDetailsResponse) Reset() {
	*x = GetScoreSheetDetailsResponse{}
	mi := &file_rpc_get_score_sheet_details_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreSheetDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreSheetDetailsResponse) ProtoMessage() {}

func (x *GetScoreSheetDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_score_sheet_details_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreSheetDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetScoreSheetDetailsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_score_sheet_details_proto_rawDescGZIP(), []int{1}
}

func (x *GetScoreSheetDetailsResponse) GetScoreSheet() *ScoreSheet {
	if x != nil {
		return x.ScoreSheet
	}
	return nil
}

func (x *GetScoreSheetDetailsResponse) GetDelegates() []*Delegate {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *GetScoreSheetDetailsResponse) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GetScoreSheetDetailsResponse) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_rpc_get_score_sheet_details_proto protoreflect.FileDescriptor

const file_rpc_get_score_sheet_details_proto_rawDesc = "" +
	"\n" +
	"!rpc_get_score_sheet_details.proto\x12\x02pb\x1a\x11score_sheet.proto\x1a\x0edelegate.proto\x1a\x0fparameter.proto\x1a\vscore.proto\"C\n" +
	"\x1bGetScoreSheetDetailsRequest\x12$\n" +
	"\x0escore_sheet_id\x18\x01 \x01(\x05R\fscoreSheetId\"\xcd\x01\n" +
	"\x1cGetScoreSheetDetailsResponse\x12/\n" +
	"\vscore_sheet\x18\x01 \x01(\v2\x0e.pb.ScoreSheetR\n" +
	"scoreSheet\x12*\n" +
	"\tdelegates\x18\x02 \x03(\v2\f.pb.DelegateR\tdelegates\x12-\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\r.pb.ParameterR\n" +
	"parameters\x12!\n" +
	"\x06scores\x18\x04 \x03(\v2\t.pb.ScoreR\x06scoresB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_get_score_sheet_details_proto_rawDescOnce sync.Once
	file_rpc_get_score_sheet_details_proto_rawDescData []byte
)

func file_rpc_get_score_sheet_details_proto_rawDescGZIP() []byte {
	file_rpc_get_score_sheet_details_proto_rawDescOnce.Do(func() {
		file_rpc_get_score_sheet_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_score_sheet_details_proto_rawDesc), len(file_rpc_get_score_sheet_details_proto_rawDesc)))
	})
	return file_rpc_get_score_sheet_details_proto_rawDescData
}

var file_rpc_get_score_sheet_details_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_score_sheet_details_proto_goTypes = []any{
	(*GetScoreSheetDetailsRequest)(nil),  // 0: pb.GetScoreSheetDetailsRequest
	(*GetScoreSheetDetailsResponse)(nil), // 1: pb.GetScoreSheetDetailsResponse
	(*ScoreSheet)(nil),                   // 2: pb.ScoreSheet
	(*Delegate)(nil),                     // 3: pb.Delegate
	(*Parameter)(nil),                    // 4: pb.Parameter
	(*Score)(nil),                        // 5: pb.Score
}
var file_rpc_get_score_sheet_details_proto_depIdxs = []int32{
	2, // 0: pb.GetScoreSheetDetailsResponse.score_sheet:type_name -> pb.ScoreSheet
	3, // 1: pb.GetScoreSheetDetailsResponse.delegates:type_name -> pb.Delegate
	4, // 2: pb.GetScoreSheetDetailsResponse.parameters:type_name -> pb.Parameter
	5, // 3: pb.GetScoreSheetDetailsResponse.scores:type_name -> pb.Score
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_get_score_sheet_details_proto_init() }
func file_rpc_get_score_sheet_details_proto_init() {
	if File_rpc_get_score_sheet_details_proto != nil {
		return
	}
	file_score_sheet_proto_init()
	file_delegate_proto_init()
	file_parameter_proto_init()
	file_score_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_score_sheet_details_proto_rawDesc), len(file_rpc_get_score_sheet_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_score_sheet_details_proto_goTypes,
		DependencyIndexes: file_rpc_get_score_sheet_details_proto_depIdxs,
		MessageInfos:      file_rpc_get_score_sheet_details_proto_msgTypes,
	}.Build()
	File_rpc_get_score_sheet_details_proto = out.File
	file_rpc_get_score_sheet_details_proto_goTypes = nil
	file_rpc_get_score_sheet_details_proto_depIdxs = nil
}
