// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_create_score_sheet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScoreSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CommitteeName string                 `protobuf:"bytes,2,opt,name=committee_name,json=committeeName,proto3" json:"committee_name,omitempty"`
	Chair         string                 `protobuf:"bytes,3,opt,name=chair,proto3" json:"chair,omitempty"`
	ViceChair     *string                `protobuf:"bytes,4,opt,name=vice_chair,json=viceChair,proto3,oneof" json:"vice_chair,omitempty"`
	Rapporteur    *string                `protobuf:"bytes,5,opt,name=rapporteur,proto3,oneof" json:"rapporteur,omitempty"`
	CreatedBy     int32                  `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScoreSheetRequest) Reset() {
	*x = CreateScoreSheetRequest{}
	mi := &file_rpc_create_score_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScoreSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScoreSheetRequest) ProtoMessage() {}

func (x *CreateScoreSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_score_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScoreSheetRequest.ProtoReflect.Descriptor instead.
func (*CreateScoreSheetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_score_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScoreSheetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScoreSheetRequest) GetCommitteeName() string {
	if x != nil {
		return x.CommitteeName
	}
	return ""
}

func (x *CreateScoreSheetRequest) GetChair() string {
	if x != nil {
		return x.Chair
	}
	return ""
}

func (x *CreateScoreSheetRequest) GetViceChair() string {
	if x != nil && x.ViceChair != nil {
		return *x.ViceChair
	}
	return ""
}

func (x *CreateScoreSheetRequest) GetRapporteur() string {
	if x != nil && x.Rapporteur != nil {
		return *x.Rapporteur
	}
	return ""
}

func (x *CreateScoreSheetRequest) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateScoreSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheet    *ScoreSheet            `protobuf:"bytes,1,opt,name=score_sheet,json=scoreSheet,proto3" json:"score_sheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScoreSheetResponse) Reset() {
	*x = CreateScoreSheetResponse{}
	mi := &file_rpc_create_score_sheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScoreSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScoreSheetResponse) ProtoMessage() {}

func (x *CreateScoreSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_score_sheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScoreSheetResponse.ProtoReflect.Descriptor instead.
func (*CreateScoreSheetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_score_sheet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScoreSheetResponse) GetScoreSheet() *ScoreSheet {
	if x != nil {
		return x.ScoreSheet
	}
	return nil
}

var File_rpc_create_score_sheet_proto protoreflect.FileDescriptor

const file_rpc_create_score_sheet_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_create_score_sheet.proto\x12\x02pb\x1a\x11score_sheet.proto\"\xf0\x01\n" +
	"\x17CreateScoreSheetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0ecommittee_name\x18\x02 \x01(\tR\rcommitteeName\x12\x14\n" +
	"\x05chair\x18\x03 \x01(\tR\x05chair\x12\"\n" +
	"\n" +
	"vice_chair\x18\x04 \x01(\tH\x00R\tviceChair\x88\x01\x01\x12#\n" +
	"\n" +
	"rapporteur\x18\x05 \x01(\tH\x01R\n" +
	"rapporteur\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\x05R\tcreatedByB\r\n" +
	"\v_vice_chairB\r\n" +
	"\v_rapporteur\"K\n" +
	"\x18CreateScoreSheetResponse\x12/\n" +
	"\vscore_sheet\x18\x01 \x01(\v2\x0e.pb.ScoreSheetR\n" +
	"scoreSheetB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_rpc_create_score_sheet_proto_rawDescOnce sync.Once
	file_rpc_create_score_sheet_proto_rawDescData []byte
)

func file_rpc_create_score_sheet_proto_rawDescGZIP() []byte {
	file_rpc_create_score_sheet_proto_rawDescOnce.Do(func() {
		file_rpc_create_score_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_score_sheet_proto_rawDesc), len(file_rpc_create_score_sheet_proto_rawDesc)))
	})
	return file_rpc_create_score_sheet_proto_rawDescData
}

var file_rpc_create_score_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_score_sheet_proto_goTypes = []any{
	(*CreateScoreSheetRequest)(nil),  // 0: pb.CreateScoreSheetRequest
	(*CreateScoreSheetResponse)(nil), // 1: pb.CreateScoreSheetResponse
	(*ScoreSheet)(nil),               // 2: pb.ScoreSheet
}
var file_rpc_create_score_sheet_proto_depIdxs = []int32{
	2, // 0: pb.CreateScoreSheetResponse.score_sheet:type_name -> pb.ScoreSheet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_score_sheet_proto_init() }
func file_rpc_create_score_sheet_proto_init() {
	if File_rpc_create_score_sheet_proto != nil {
		return
	}
	file_score_sheet_proto_init()
	file_rpc_create_score_sheet_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_score_sheet_proto_rawDesc), len(file_rpc_create_score_sheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_score_sheet_proto_goTypes,
		DependencyIndexes: file_rpc_create_score_sheet_proto_depIdxs,
		MessageInfos:      file_rpc_create_score_sheet_proto_msgTypes,
	}.Build()
	File_rpc_create_score_sheet_proto = out.File
	file_rpc_create_score_sheet_proto_goTypes = nil
	file_rpc_create_score_sheet_proto_depIdxs = nil
}
