// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_get_delegate_by_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDelegateByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelegateId    int32                  `protobuf:"varint,1,opt,name=delegate_id,json=delegateId,proto3" json:"delegate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegateByIdRequest) Reset() {
	*x = GetDelegateByIdRequest{}
	mi := &file_rpc_get_delegate_by_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegateByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegateByIdRequest) ProtoMessage() {}

func (x *GetDelegateByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_delegate_by_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegateByIdRequest.ProtoReflect.Descriptor instead.
func (*GetDelegateByIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_delegate_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetDelegateByIdRequest) GetDelegateId() int32 {
	if x != nil {
		return x.DelegateId
	}
	return 0
}

type GetDelegateByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegate      *Delegate              `protobuf:"bytes,1,opt,name=delegate,proto3" json:"delegate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegateByIdResponse) Reset() {
	*x = GetDelegateByIdResponse{}
	mi := &file_rpc_get_delegate_by_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegateByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegateByIdResponse) ProtoMessage() {}

func (x *GetDelegateByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_delegate_by_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegateByIdResponse.ProtoReflect.Descriptor instead.
func (*GetDelegateByIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_delegate_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetDelegateByIdResponse) GetDelegate() *Delegate {
	if x != nil {
		return x.Delegate
	}
	return nil
}

var File_rpc_get_delegate_by_id_proto protoreflect.FileDescriptor

const file_rpc_get_delegate_by_id_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_get_delegate_by_id.proto\x12\x02pb\x1a\x0edelegate.proto\"9\n" +
	"\x16GetDelegateByIdRequest\x12\x1f\n" +
	"\vdelegate_id\x18\x01 \x01(\x05R\n" +
	"delegateId\"C\n" +
	"\x17GetDelegateByIdResponse\x12(\n" +
	"\bdelegate\x18\x01 \x01(\v2\f.pb.DelegateR\bdelegateB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_rpc_get_delegate_by_id_proto_rawDescOnce sync.Once
	file_rpc_get_delegate_by_id_proto_rawDescData []byte
)

func file_rpc_get_delegate_by_id_proto_rawDescGZIP() []byte {
	file_rpc_get_delegate_by_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_delegate_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_delegate_by_id_proto_rawDesc), len(file_rpc_get_delegate_by_id_proto_rawDesc)))
	})
	return file_rpc_get_delegate_by_id_proto_rawDescData
}

var file_rpc_get_delegate_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_delegate_by_id_proto_goTypes = []any{
	(*GetDelegateByIdRequest)(nil),  // 0: pb.GetDelegateByIdRequest
	(*GetDelegateByIdResponse)(nil), // 1: pb.GetDelegateByIdResponse
	(*Delegate)(nil),                // 2: pb.Delegate
}
var file_rpc_get_delegate_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetDelegateByIdResponse.delegate:type_name -> pb.Delegate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_delegate_by_id_proto_init() }
func file_rpc_get_delegate_by_id_proto_init() {
	if File_rpc_get_delegate_by_id_proto != nil {
		return
	}
	file_delegate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_delegate_by_id_proto_rawDesc), len(file_rpc_get_delegate_by_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_delegate_by_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_delegate_by_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_delegate_by_id_proto_msgTypes,
	}.Build()
	File_rpc_get_delegate_by_id_proto = out.File
	file_rpc_get_delegate_by_id_proto_goTypes = nil
	file_rpc_get_delegate_by_id_proto_depIdxs = nil
}
