// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_delete_delegate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteDelegateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelegateId    int32                  `protobuf:"varint,1,opt,name=delegate_id,json=delegateId,proto3" json:"delegate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDelegateRequest) Reset() {
	*x = DeleteDelegateRequest{}
	mi := &file_rpc_delete_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDelegateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDelegateRequest) ProtoMessage() {}

func (x *DeleteDelegateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDelegateRequest.ProtoReflect.Descriptor instead.
func (*DeleteDelegateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteDelegateRequest) GetDelegateId() int32 {
	if x != nil {
		return x.DelegateId
	}
	return 0
}

type DeleteDelegateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDelegateResponse) Reset() {
	*x = DeleteDelegateResponse{}
	mi := &file_rpc_delete_delegate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDelegateResponse) ProtoMessage() {}

func (x *DeleteDelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_delegate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDelegateResponse.ProtoReflect.Descriptor instead.
func (*DeleteDelegateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_delegate_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteDelegateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_delete_delegate_proto protoreflect.FileDescriptor

const file_rpc_delete_delegate_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_delete_delegate.proto\x12\x02pb\"8\n" +
	"\x15DeleteDelegateRequest\x12\x1f\n" +
	"\vdelegate_id\x18\x01 \x01(\x05R\n" +
	"delegateId\"2\n" +
	"\x16DeleteDelegateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_delete_delegate_proto_rawDescOnce sync.Once
	file_rpc_delete_delegate_proto_rawDescData []byte
)

func file_rpc_delete_delegate_proto_rawDescGZIP() []byte {
	file_rpc_delete_delegate_proto_rawDescOnce.Do(func() {
		file_rpc_delete_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_delegate_proto_rawDesc), len(file_rpc_delete_delegate_proto_rawDesc)))
	})
	return file_rpc_delete_delegate_proto_rawDescData
}

var file_rpc_delete_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_delegate_proto_goTypes = []any{
	(*DeleteDelegateRequest)(nil),  // 0: pb.DeleteDelegateRequest
	(*DeleteDelegateResponse)(nil), // 1: pb.DeleteDelegateResponse
}
var file_rpc_delete_delegate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_delegate_proto_init() }
func file_rpc_delete_delegate_proto_init() {
	if File_rpc_delete_delegate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_delegate_proto_rawDesc), len(file_rpc_delete_delegate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_delegate_proto_goTypes,
		DependencyIndexes: file_rpc_delete_delegate_proto_depIdxs,
		MessageInfos:      file_rpc_delete_delegate_proto_msgTypes,
	}.Build()
	File_rpc_delete_delegate_proto = out.File
	file_rpc_delete_delegate_proto_goTypes = nil
	file_rpc_delete_delegate_proto_depIdxs = nil
}
