// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_get_user_by_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_rpc_get_user_by_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_user_by_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_user_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_rpc_get_user_by_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_user_by_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_user_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_rpc_get_user_by_id_proto protoreflect.FileDescriptor

const file_rpc_get_user_by_id_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_get_user_by_id.proto\x12\x02pb\x1a\n" +
	"user.proto\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"3\n" +
	"\x13GetUserByIdResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.pb.UserR\x04userB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_get_user_by_id_proto_rawDescOnce sync.Once
	file_rpc_get_user_by_id_proto_rawDescData []byte
)

func file_rpc_get_user_by_id_proto_rawDescGZIP() []byte {
	file_rpc_get_user_by_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_user_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_user_by_id_proto_rawDesc), len(file_rpc_get_user_by_id_proto_rawDesc)))
	})
	return file_rpc_get_user_by_id_proto_rawDescData
}

var file_rpc_get_user_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_user_by_id_proto_goTypes = []any{
	(*GetUserByIdRequest)(nil),  // 0: pb.GetUserByIdRequest
	(*GetUserByIdResponse)(nil), // 1: pb.GetUserByIdResponse
	(*User)(nil),                // 2: pb.User
}
var file_rpc_get_user_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetUserByIdResponse.user:type_name -> pb.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_user_by_id_proto_init() }
func file_rpc_get_user_by_id_proto_init() {
	if File_rpc_get_user_by_id_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_user_by_id_proto_rawDesc), len(file_rpc_get_user_by_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_user_by_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_user_by_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_user_by_id_proto_msgTypes,
	}.Build()
	File_rpc_get_user_by_id_proto = out.File
	file_rpc_get_user_by_id_proto_goTypes = nil
	file_rpc_get_user_by_id_proto_depIdxs = nil
}
