// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_create_score.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelegateId    int32                  `protobuf:"varint,1,opt,name=delegate_id,json=delegateId,proto3" json:"delegate_id,omitempty"`
	ParameterId   int32                  `protobuf:"varint,2,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Note          *string                `protobuf:"bytes,4,opt,name=note,proto3,oneof" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScoreRequest) Reset() {
	*x = CreateScoreRequest{}
	mi := &file_rpc_create_score_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScoreRequest) ProtoMessage() {}

func (x *CreateScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_score_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScoreRequest.ProtoReflect.Descriptor instead.
func (*CreateScoreRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_score_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScoreRequest) GetDelegateId() int32 {
	if x != nil {
		return x.DelegateId
	}
	return 0
}

func (x *CreateScoreRequest) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *CreateScoreRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateScoreRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type CreateScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *Score                 `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScoreResponse) Reset() {
	*x = CreateScoreResponse{}
	mi := &file_rpc_create_score_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScoreResponse) ProtoMessage() {}

func (x *CreateScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_score_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScoreResponse.ProtoReflect.Descriptor instead.
func (*CreateScoreResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_score_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScoreResponse) GetScore() *Score {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_rpc_create_score_proto protoreflect.FileDescriptor

const file_rpc_create_score_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_create_score.proto\x12\x02pb\x1a\vscore.proto\"\x90\x01\n" +
	"\x12CreateScoreRequest\x12\x1f\n" +
	"\vdelegate_id\x18\x01 \x01(\x05R\n" +
	"delegateId\x12!\n" +
	"\fparameter_id\x18\x02 \x01(\x05R\vparameterId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x17\n" +
	"\x04note\x18\x04 \x01(\tH\x00R\x04note\x88\x01\x01B\a\n" +
	"\x05_note\"6\n" +
	"\x13CreateScoreResponse\x12\x1f\n" +
	"\x05score\x18\x01 \x01(\v2\t.pb.ScoreR\x05scoreB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_create_score_proto_rawDescOnce sync.Once
	file_rpc_create_score_proto_rawDescData []byte
)

func file_rpc_create_score_proto_rawDescGZIP() []byte {
	file_rpc_create_score_proto_rawDescOnce.Do(func() {
		file_rpc_create_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_score_proto_rawDesc), len(file_rpc_create_score_proto_rawDesc)))
	})
	return file_rpc_create_score_proto_rawDescData
}

var file_rpc_create_score_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_score_proto_goTypes = []any{
	(*CreateScoreRequest)(nil),  // 0: pb.CreateScoreRequest
	(*CreateScoreResponse)(nil), // 1: pb.CreateScoreResponse
	(*Score)(nil),               // 2: pb.Score
}
var file_rpc_create_score_proto_depIdxs = []int32{
	2, // 0: pb.CreateScoreResponse.score:type_name -> pb.Score
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_score_proto_init() }
func file_rpc_create_score_proto_init() {
	if File_rpc_create_score_proto != nil {
		return
	}
	file_score_proto_init()
	file_rpc_create_score_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_score_proto_rawDesc), len(file_rpc_create_score_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_score_proto_goTypes,
		DependencyIndexes: file_rpc_create_score_proto_depIdxs,
		MessageInfos:      file_rpc_create_score_proto_msgTypes,
	}.Build()
	File_rpc_create_score_proto = out.File
	file_rpc_create_score_proto_goTypes = nil
	file_rpc_create_score_proto_depIdxs = nil
}
