// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_delete_score_sheet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteScoreSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheetId  int32                  `protobuf:"varint,1,opt,name=score_sheet_id,json=scoreSheetId,proto3" json:"score_sheet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScoreSheetRequest) Reset() {
	*x = DeleteScoreSheetRequest{}
	mi := &file_rpc_delete_score_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScoreSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoreSheetRequest) ProtoMessage() {}

func (x *DeleteScoreSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_score_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoreSheetRequest.ProtoReflect.Descriptor instead.
func (*DeleteScoreSheetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_score_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteScoreSheetRequest) GetScoreSheetId() int32 {
	if x != nil {
		return x.ScoreSheetId
	}
	return 0
}

type DeleteScoreSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message for success or error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScoreSheetResponse) Reset() {
	*x = DeleteScoreSheetResponse{}
	mi := &file_rpc_delete_score_sheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScoreSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoreSheetResponse) ProtoMessage() {}

func (x *DeleteScoreSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_score_sheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoreSheetResponse.ProtoReflect.Descriptor instead.
func (*DeleteScoreSheetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_score_sheet_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteScoreSheetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteScoreSheetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_delete_score_sheet_proto protoreflect.FileDescriptor

const file_rpc_delete_score_sheet_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_delete_score_sheet.proto\x12\x02pb\"?\n" +
	"\x17DeleteScoreSheetRequest\x12$\n" +
	"\x0escore_sheet_id\x18\x01 \x01(\x05R\fscoreSheetId\"N\n" +
	"\x18DeleteScoreSheetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_delete_score_sheet_proto_rawDescOnce sync.Once
	file_rpc_delete_score_sheet_proto_rawDescData []byte
)

func file_rpc_delete_score_sheet_proto_rawDescGZIP() []byte {
	file_rpc_delete_score_sheet_proto_rawDescOnce.Do(func() {
		file_rpc_delete_score_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_score_sheet_proto_rawDesc), len(file_rpc_delete_score_sheet_proto_rawDesc)))
	})
	return file_rpc_delete_score_sheet_proto_rawDescData
}

var file_rpc_delete_score_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_score_sheet_proto_goTypes = []any{
	(*DeleteScoreSheetRequest)(nil),  // 0: pb.DeleteScoreSheetRequest
	(*DeleteScoreSheetResponse)(nil), // 1: pb.DeleteScoreSheetResponse
}
var file_rpc_delete_score_sheet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_score_sheet_proto_init() }
func file_rpc_delete_score_sheet_proto_init() {
	if File_rpc_delete_score_sheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_score_sheet_proto_rawDesc), len(file_rpc_delete_score_sheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_score_sheet_proto_goTypes,
		DependencyIndexes: file_rpc_delete_score_sheet_proto_depIdxs,
		MessageInfos:      file_rpc_delete_score_sheet_proto_msgTypes,
	}.Build()
	File_rpc_delete_score_sheet_proto = out.File
	file_rpc_delete_score_sheet_proto_goTypes = nil
	file_rpc_delete_score_sheet_proto_depIdxs = nil
}
