// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_update_parameter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateParameterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ParameterId        int32                  `protobuf:"varint,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	Name               *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	RuleType           *string                `protobuf:"bytes,3,opt,name=rule_type,json=ruleType,proto3,oneof" json:"rule_type,omitempty"`
	IsSpecialParameter *bool                  `protobuf:"varint,4,opt,name=is_special_parameter,json=isSpecialParameter,proto3,oneof" json:"is_special_parameter,omitempty"`
	SpecialScoresRule  *string                `protobuf:"bytes,5,opt,name=special_scores_rule,json=specialScoresRule,proto3,oneof" json:"special_scores_rule,omitempty"`
	SpecialLengthRule  *string                `protobuf:"bytes,6,opt,name=special_length_rule,json=specialLengthRule,proto3,oneof" json:"special_length_rule,omitempty"`
	ScoreWeight        *float64               `protobuf:"fixed64,7,opt,name=score_weight,json=scoreWeight,proto3,oneof" json:"score_weight,omitempty"`
	LengthWeight       *float64               `protobuf:"fixed64,8,opt,name=length_weight,json=lengthWeight,proto3,oneof" json:"length_weight,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateParameterRequest) Reset() {
	*x = UpdateParameterRequest{}
	mi := &file_rpc_update_parameter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParameterRequest) ProtoMessage() {}

func (x *UpdateParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_parameter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParameterRequest.ProtoReflect.Descriptor instead.
func (*UpdateParameterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_parameter_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateParameterRequest) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *UpdateParameterRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateParameterRequest) GetRuleType() string {
	if x != nil && x.RuleType != nil {
		return *x.RuleType
	}
	return ""
}

func (x *UpdateParameterRequest) GetIsSpecialParameter() bool {
	if x != nil && x.IsSpecialParameter != nil {
		return *x.IsSpecialParameter
	}
	return false
}

func (x *UpdateParameterRequest) GetSpecialScoresRule() string {
	if x != nil && x.SpecialScoresRule != nil {
		return *x.SpecialScoresRule
	}
	return ""
}

func (x *UpdateParameterRequest) GetSpecialLengthRule() string {
	if x != nil && x.SpecialLengthRule != nil {
		return *x.SpecialLengthRule
	}
	return ""
}

func (x *UpdateParameterRequest) GetScoreWeight() float64 {
	if x != nil && x.ScoreWeight != nil {
		return *x.ScoreWeight
	}
	return 0
}

func (x *UpdateParameterRequest) GetLengthWeight() float64 {
	if x != nil && x.LengthWeight != nil {
		return *x.LengthWeight
	}
	return 0
}

type UpdateParameterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     *Parameter             `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParameterResponse) Reset() {
	*x = UpdateParameterResponse{}
	mi := &file_rpc_update_parameter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParameterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParameterResponse) ProtoMessage() {}

func (x *UpdateParameterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_parameter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParameterResponse.ProtoReflect.Descriptor instead.
func (*UpdateParameterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_parameter_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateParameterResponse) GetParameter() *Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

var File_rpc_update_parameter_proto protoreflect.FileDescriptor

const file_rpc_update_parameter_proto_rawDesc = "" +
	"\n" +
	"\x1arpc_update_parameter.proto\x12\x02pb\x1a\x0fparameter.proto\"\xec\x03\n" +
	"\x16UpdateParameterRequest\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\x05R\vparameterId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\trule_type\x18\x03 \x01(\tH\x01R\bruleType\x88\x01\x01\x125\n" +
	"\x14is_special_parameter\x18\x04 \x01(\bH\x02R\x12isSpecialParameter\x88\x01\x01\x123\n" +
	"\x13special_scores_rule\x18\x05 \x01(\tH\x03R\x11specialScoresRule\x88\x01\x01\x123\n" +
	"\x13special_length_rule\x18\x06 \x01(\tH\x04R\x11specialLengthRule\x88\x01\x01\x12&\n" +
	"\fscore_weight\x18\a \x01(\x01H\x05R\vscoreWeight\x88\x01\x01\x12(\n" +
	"\rlength_weight\x18\b \x01(\x01H\x06R\flengthWeight\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_rule_typeB\x17\n" +
	"\x15_is_special_parameterB\x16\n" +
	"\x14_special_scores_ruleB\x16\n" +
	"\x14_special_length_ruleB\x0f\n" +
	"\r_score_weightB\x10\n" +
	"\x0e_length_weight\"F\n" +
	"\x17UpdateParameterResponse\x12+\n" +
	"\tparameter\x18\x01 \x01(\v2\r.pb.ParameterR\tparameterB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_update_parameter_proto_rawDescOnce sync.Once
	file_rpc_update_parameter_proto_rawDescData []byte
)

func file_rpc_update_parameter_proto_rawDescGZIP() []byte {
	file_rpc_update_parameter_proto_rawDescOnce.Do(func() {
		file_rpc_update_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_parameter_proto_rawDesc), len(file_rpc_update_parameter_proto_rawDesc)))
	})
	return file_rpc_update_parameter_proto_rawDescData
}

var file_rpc_update_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_parameter_proto_goTypes = []any{
	(*UpdateParameterRequest)(nil),  // 0: pb.UpdateParameterRequest
	(*UpdateParameterResponse)(nil), // 1: pb.UpdateParameterResponse
	(*Parameter)(nil),               // 2: pb.Parameter
}
var file_rpc_update_parameter_proto_depIdxs = []int32{
	2, // 0: pb.UpdateParameterResponse.parameter:type_name -> pb.Parameter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_parameter_proto_init() }
func file_rpc_update_parameter_proto_init() {
	if File_rpc_update_parameter_proto != nil {
		return
	}
	file_parameter_proto_init()
	file_rpc_update_parameter_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_parameter_proto_rawDesc), len(file_rpc_update_parameter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_parameter_proto_goTypes,
		DependencyIndexes: file_rpc_update_parameter_proto_depIdxs,
		MessageInfos:      file_rpc_update_parameter_proto_msgTypes,
	}.Build()
	File_rpc_update_parameter_proto = out.File
	file_rpc_update_parameter_proto_goTypes = nil
	file_rpc_update_parameter_proto_depIdxs = nil
}
