// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_get_score_sheet_by_user_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScoreSheetByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreSheetByUserIdRequest) Reset() {
	*x = GetScoreSheetByUserIdRequest{}
	mi := &file_rpc_get_score_sheet_by_user_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreSheetByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreSheetByUserIdRequest) ProtoMessage() {}

func (x *GetScoreSheetByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_score_sheet_by_user_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreSheetByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetScoreSheetByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_score_sheet_by_user_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetScoreSheetByUserIdRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetScoreSheetByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheets   []*ScoreSheet          `protobuf:"bytes,1,rep,name=score_sheets,json=scoreSheets,proto3" json:"score_sheets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreSheetByUserIdResponse) Reset() {
	*x = GetScoreSheetByUserIdResponse{}
	mi := &file_rpc_get_score_sheet_by_user_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreSheetByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreSheetByUserIdResponse) ProtoMessage() {}

func (x *GetScoreSheetByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_score_sheet_by_user_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreSheetByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetScoreSheetByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_score_sheet_by_user_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetScoreSheetByUserIdResponse) GetScoreSheets() []*ScoreSheet {
	if x != nil {
		return x.ScoreSheets
	}
	return nil
}

var File_rpc_get_score_sheet_by_user_id_proto protoreflect.FileDescriptor

const file_rpc_get_score_sheet_by_user_id_proto_rawDesc = "" +
	"\n" +
	"$rpc_get_score_sheet_by_user_id.proto\x12\x02pb\x1a\x11score_sheet.proto\"7\n" +
	"\x1cGetScoreSheetByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"R\n" +
	"\x1dGetScoreSheetByUserIdResponse\x121\n" +
	"\fscore_sheets\x18\x01 \x03(\v2\x0e.pb.ScoreSheetR\vscoreSheetsB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_rpc_get_score_sheet_by_user_id_proto_rawDescOnce sync.Once
	file_rpc_get_score_sheet_by_user_id_proto_rawDescData []byte
)

func file_rpc_get_score_sheet_by_user_id_proto_rawDescGZIP() []byte {
	file_rpc_get_score_sheet_by_user_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_score_sheet_by_user_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_score_sheet_by_user_id_proto_rawDesc), len(file_rpc_get_score_sheet_by_user_id_proto_rawDesc)))
	})
	return file_rpc_get_score_sheet_by_user_id_proto_rawDescData
}

var file_rpc_get_score_sheet_by_user_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_score_sheet_by_user_id_proto_goTypes = []any{
	(*GetScoreSheetByUserIdRequest)(nil),  // 0: pb.GetScoreSheetByUserIdRequest
	(*GetScoreSheetByUserIdResponse)(nil), // 1: pb.GetScoreSheetByUserIdResponse
	(*ScoreSheet)(nil),                    // 2: pb.ScoreSheet
}
var file_rpc_get_score_sheet_by_user_id_proto_depIdxs = []int32{
	2, // 0: pb.GetScoreSheetByUserIdResponse.score_sheets:type_name -> pb.ScoreSheet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_score_sheet_by_user_id_proto_init() }
func file_rpc_get_score_sheet_by_user_id_proto_init() {
	if File_rpc_get_score_sheet_by_user_id_proto != nil {
		return
	}
	file_score_sheet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_score_sheet_by_user_id_proto_rawDesc), len(file_rpc_get_score_sheet_by_user_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_score_sheet_by_user_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_score_sheet_by_user_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_score_sheet_by_user_id_proto_msgTypes,
	}.Build()
	File_rpc_get_score_sheet_by_user_id_proto = out.File
	file_rpc_get_score_sheet_by_user_id_proto_goTypes = nil
	file_rpc_get_score_sheet_by_user_id_proto_depIdxs = nil
}
