// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_create_delegate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDelegateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreSheetId  int32                  `protobuf:"varint,1,opt,name=score_sheet_id,json=scoreSheetId,proto3" json:"score_sheet_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDelegateRequest) Reset() {
	*x = CreateDelegateRequest{}
	mi := &file_rpc_create_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDelegateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDelegateRequest) ProtoMessage() {}

func (x *CreateDelegateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDelegateRequest.ProtoReflect.Descriptor instead.
func (*CreateDelegateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDelegateRequest) GetScoreSheetId() int32 {
	if x != nil {
		return x.ScoreSheetId
	}
	return 0
}

func (x *CreateDelegateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDelegateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegate      *Delegate              `protobuf:"bytes,1,opt,name=delegate,proto3" json:"delegate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDelegateResponse) Reset() {
	*x = CreateDelegateResponse{}
	mi := &file_rpc_create_delegate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDelegateResponse) ProtoMessage() {}

func (x *CreateDelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_delegate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDelegateResponse.ProtoReflect.Descriptor instead.
func (*CreateDelegateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_delegate_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDelegateResponse) GetDelegate() *Delegate {
	if x != nil {
		return x.Delegate
	}
	return nil
}

var File_rpc_create_delegate_proto protoreflect.FileDescriptor

const file_rpc_create_delegate_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_create_delegate.proto\x12\x02pb\x1a\x0edelegate.proto\"Q\n" +
	"\x15CreateDelegateRequest\x12$\n" +
	"\x0escore_sheet_id\x18\x01 \x01(\x05R\fscoreSheetId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x16CreateDelegateResponse\x12(\n" +
	"\bdelegate\x18\x01 \x01(\v2\f.pb.DelegateR\bdelegateB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_rpc_create_delegate_proto_rawDescOnce sync.Once
	file_rpc_create_delegate_proto_rawDescData []byte
)

func file_rpc_create_delegate_proto_rawDescGZIP() []byte {
	file_rpc_create_delegate_proto_rawDescOnce.Do(func() {
		file_rpc_create_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_delegate_proto_rawDesc), len(file_rpc_create_delegate_proto_rawDesc)))
	})
	return file_rpc_create_delegate_proto_rawDescData
}

var file_rpc_create_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_delegate_proto_goTypes = []any{
	(*CreateDelegateRequest)(nil),  // 0: pb.CreateDelegateRequest
	(*CreateDelegateResponse)(nil), // 1: pb.CreateDelegateResponse
	(*Delegate)(nil),               // 2: pb.Delegate
}
var file_rpc_create_delegate_proto_depIdxs = []int32{
	2, // 0: pb.CreateDelegateResponse.delegate:type_name -> pb.Delegate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_delegate_proto_init() }
func file_rpc_create_delegate_proto_init() {
	if File_rpc_create_delegate_proto != nil {
		return
	}
	file_delegate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_delegate_proto_rawDesc), len(file_rpc_create_delegate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_delegate_proto_goTypes,
		DependencyIndexes: file_rpc_create_delegate_proto_depIdxs,
		MessageInfos:      file_rpc_create_delegate_proto_msgTypes,
	}.Build()
	File_rpc_create_delegate_proto = out.File
	file_rpc_create_delegate_proto_goTypes = nil
	file_rpc_create_delegate_proto_depIdxs = nil
}
