// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_get_parameter_by_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetParameterByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterId   int32                  `protobuf:"varint,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParameterByIdRequest) Reset() {
	*x = GetParameterByIdRequest{}
	mi := &file_rpc_get_parameter_by_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParameterByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterByIdRequest) ProtoMessage() {}

func (x *GetParameterByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_parameter_by_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterByIdRequest.ProtoReflect.Descriptor instead.
func (*GetParameterByIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_parameter_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetParameterByIdRequest) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

type GetParameterByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     *Parameter             `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParameterByIdResponse) Reset() {
	*x = GetParameterByIdResponse{}
	mi := &file_rpc_get_parameter_by_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParameterByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterByIdResponse) ProtoMessage() {}

func (x *GetParameterByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_parameter_by_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterByIdResponse.ProtoReflect.Descriptor instead.
func (*GetParameterByIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_parameter_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetParameterByIdResponse) GetParameter() *Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

var File_rpc_get_parameter_by_id_proto protoreflect.FileDescriptor

const file_rpc_get_parameter_by_id_proto_rawDesc = "" +
	"\n" +
	"\x1drpc_get_parameter_by_id.proto\x12\x02pb\x1a\x0fparameter.proto\"<\n" +
	"\x17GetParameterByIdRequest\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\x05R\vparameterId\"G\n" +
	"\x18GetParameterByIdResponse\x12+\n" +
	"\tparameter\x18\x01 \x01(\v2\r.pb.ParameterR\tparameterB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_rpc_get_parameter_by_id_proto_rawDescOnce sync.Once
	file_rpc_get_parameter_by_id_proto_rawDescData []byte
)

func file_rpc_get_parameter_by_id_proto_rawDescGZIP() []byte {
	file_rpc_get_parameter_by_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_parameter_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_parameter_by_id_proto_rawDesc), len(file_rpc_get_parameter_by_id_proto_rawDesc)))
	})
	return file_rpc_get_parameter_by_id_proto_rawDescData
}

var file_rpc_get_parameter_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_parameter_by_id_proto_goTypes = []any{
	(*GetParameterByIdRequest)(nil),  // 0: pb.GetParameterByIdRequest
	(*GetParameterByIdResponse)(nil), // 1: pb.GetParameterByIdResponse
	(*Parameter)(nil),                // 2: pb.Parameter
}
var file_rpc_get_parameter_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetParameterByIdResponse.parameter:type_name -> pb.Parameter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_parameter_by_id_proto_init() }
func file_rpc_get_parameter_by_id_proto_init() {
	if File_rpc_get_parameter_by_id_proto != nil {
		return
	}
	file_parameter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_parameter_by_id_proto_rawDesc), len(file_rpc_get_parameter_by_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_parameter_by_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_parameter_by_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_parameter_by_id_proto_msgTypes,
	}.Build()
	File_rpc_get_parameter_by_id_proto = out.File
	file_rpc_get_parameter_by_id_proto_goTypes = nil
	file_rpc_get_parameter_by_id_proto_depIdxs = nil
}
