// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: score_sheet.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommitteeName string                 `protobuf:"bytes,3,opt,name=committee_name,json=committeeName,proto3" json:"committee_name,omitempty"`
	Chair         string                 `protobuf:"bytes,4,opt,name=chair,proto3" json:"chair,omitempty"`
	ViceChair     string                 `protobuf:"bytes,5,opt,name=vice_chair,json=viceChair,proto3" json:"vice_chair,omitempty"`
	Rapporteur    string                 `protobuf:"bytes,6,opt,name=rapporteur,proto3" json:"rapporteur,omitempty"`
	CreatedBy     int32                  `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreSheet) Reset() {
	*x = ScoreSheet{}
	mi := &file_score_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreSheet) ProtoMessage() {}

func (x *ScoreSheet) ProtoReflect() protoreflect.Message {
	mi := &file_score_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreSheet.ProtoReflect.Descriptor instead.
func (*ScoreSheet) Descriptor() ([]byte, []int) {
	return file_score_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreSheet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScoreSheet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScoreSheet) GetCommitteeName() string {
	if x != nil {
		return x.CommitteeName
	}
	return ""
}

func (x *ScoreSheet) GetChair() string {
	if x != nil {
		return x.Chair
	}
	return ""
}

func (x *ScoreSheet) GetViceChair() string {
	if x != nil {
		return x.ViceChair
	}
	return ""
}

func (x *ScoreSheet) GetRapporteur() string {
	if x != nil {
		return x.Rapporteur
	}
	return ""
}

func (x *ScoreSheet) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *ScoreSheet) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScoreSheet) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_score_sheet_proto protoreflect.FileDescriptor

const file_score_sheet_proto_rawDesc = "" +
	"\n" +
	"\x11score_sheet.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\n" +
	"ScoreSheet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0ecommittee_name\x18\x03 \x01(\tR\rcommitteeName\x12\x14\n" +
	"\x05chair\x18\x04 \x01(\tR\x05chair\x12\x1d\n" +
	"\n" +
	"vice_chair\x18\x05 \x01(\tR\tviceChair\x12\x1e\n" +
	"\n" +
	"rapporteur\x18\x06 \x01(\tR\n" +
	"rapporteur\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\x05R\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB7Z5github.com/DebdipWritesCode/MUN_Scoresheet/backend/pbb\x06proto3"

var (
	file_score_sheet_proto_rawDescOnce sync.Once
	file_score_sheet_proto_rawDescData []byte
)

func file_score_sheet_proto_rawDescGZIP() []byte {
	file_score_sheet_proto_rawDescOnce.Do(func() {
		file_score_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_score_sheet_proto_rawDesc), len(file_score_sheet_proto_rawDesc)))
	})
	return file_score_sheet_proto_rawDescData
}

var file_score_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_score_sheet_proto_goTypes = []any{
	(*ScoreSheet)(nil),          // 0: pb.ScoreSheet
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_score_sheet_proto_depIdxs = []int32{
	1, // 0: pb.ScoreSheet.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: pb.ScoreSheet.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_score_sheet_proto_init() }
func file_score_sheet_proto_init() {
	if File_score_sheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_score_sheet_proto_rawDesc), len(file_score_sheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_score_sheet_proto_goTypes,
		DependencyIndexes: file_score_sheet_proto_depIdxs,
		MessageInfos:      file_score_sheet_proto_msgTypes,
	}.Build()
	File_score_sheet_proto = out.File
	file_score_sheet_proto_goTypes = nil
	file_score_sheet_proto_depIdxs = nil
}
