// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: score.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DelegateId    int32                  `protobuf:"varint,2,opt,name=delegate_id,json=delegateId,proto3" json:"delegate_id,omitempty"`
	ParameterId   int32                  `protobuf:"varint,3,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_score_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_score_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_score_proto_rawDescGZIP(), []int{0}
}

func (x *Score) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Score) GetDelegateId() int32 {
	if x != nil {
		return x.DelegateId
	}
	return 0
}

func (x *Score) GetParameterId() int32 {
	if x != nil {
		return x.ParameterId
	}
	return 0
}

func (x *Score) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Score) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_score_proto protoreflect.FileDescriptor

const file_score_proto_rawDesc = "" +
	"\n" +
	"\vscore.proto\x12\x02pb\"\x85\x01\n" +
	"\x05Score\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vdelegate_id\x18\x02 \x01(\x05R\n" +
	"delegateId\x12!\n" +
	"\fparameter_id\x18\x03 \x01(\x05R\vparameterId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04noteB1Z/github.com/DebdipWritesCode/Munshiji/backend/pbb\x06proto3"

var (
	file_score_proto_rawDescOnce sync.Once
	file_score_proto_rawDescData []byte
)

func file_score_proto_rawDescGZIP() []byte {
	file_score_proto_rawDescOnce.Do(func() {
		file_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_score_proto_rawDesc), len(file_score_proto_rawDesc)))
	})
	return file_score_proto_rawDescData
}

var file_score_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_score_proto_goTypes = []any{
	(*Score)(nil), // 0: pb.Score
}
var file_score_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_score_proto_init() }
func file_score_proto_init() {
	if File_score_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_score_proto_rawDesc), len(file_score_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_score_proto_goTypes,
		DependencyIndexes: file_score_proto_depIdxs,
		MessageInfos:      file_score_proto_msgTypes,
	}.Build()
	File_score_proto = out.File
	file_score_proto_goTypes = nil
	file_score_proto_depIdxs = nil
}
