CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "jwt_token" varchar NOT NULL,
  "refresh_token" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp,
  "refresh_expires_at" timestamp NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "score_sheets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL DEFAULT 'New Score Sheet',
  "committee_name" varchar NOT NULL,
  "chair" varchar NOT NULL,
  "vice_chair" varchar,
  "rapporteur" varchar,
  "created_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "delegates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "score_sheet_id" integer NOT NULL,
  "name" varchar NOT NULL,
  UNIQUE ("score_sheet_id", "name"),
  FOREIGN KEY ("score_sheet_id") REFERENCES "score_sheets" ("id") ON DELETE CASCADE
);

CREATE TABLE "parameters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "score_sheet_id" integer NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "rule_type" varchar NOT NULL CHECK (rule_type IN ('average', 'absolute', 'special')),
  "is_special_parameter" bool NOT NULL DEFAULT false,
  "special_scores_rule" varchar CHECK (special_scores_rule IN ('average', 'absolute')),
  "special_length_rule" varchar CHECK (special_length_rule IN ('average', 'absolute')),
  "score_weight" float DEFAULT 1 CHECK (score_weight >= 0 AND score_weight <= 1),
  "length_weight" float DEFAULT 1 CHECK (length_weight >= 0 AND length_weight <= 1),
  UNIQUE ("score_sheet_id", "name"),
  FOREIGN KEY ("score_sheet_id") REFERENCES "score_sheets" ("id") ON DELETE CASCADE
);

CREATE TABLE "scores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "delegate_id" integer NOT NULL,
  "parameter_id" integer NOT NULL,
  "value" float NOT NULL,
  "note" varchar CHECK (length(note) <= 5),
  FOREIGN KEY ("delegate_id") REFERENCES "delegates" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("parameter_id") REFERENCES "parameters" ("id") ON DELETE CASCADE
);
