// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type AiSession struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
	Prompt    string         `json:"prompt"`
	Status    sql.NullString `json:"status"`
}

type Delegate struct {
	ID           int32  `json:"id"`
	ScoreSheetID int32  `json:"score_sheet_id"`
	Name         string `json:"name"`
}

type Parameter struct {
	ID                 int32           `json:"id"`
	ScoreSheetID       int32           `json:"score_sheet_id"`
	Name               string          `json:"name"`
	RuleType           string          `json:"rule_type"`
	IsSpecialParameter bool            `json:"is_special_parameter"`
	SpecialScoresRule  sql.NullString  `json:"special_scores_rule"`
	SpecialLengthRule  sql.NullString  `json:"special_length_rule"`
	ScoreWeight        sql.NullFloat64 `json:"score_weight"`
	LengthWeight       sql.NullFloat64 `json:"length_weight"`
}

type Score struct {
	ID          int32          `json:"id"`
	DelegateID  int32          `json:"delegate_id"`
	ParameterID int32          `json:"parameter_id"`
	Value       float64        `json:"value"`
	Note        sql.NullString `json:"note"`
}

type ScoreSheet struct {
	ID            int32          `json:"id"`
	Name          string         `json:"name"`
	CommitteeName string         `json:"committee_name"`
	Chair         string         `json:"chair"`
	ViceChair     sql.NullString `json:"vice_chair"`
	Rapporteur    sql.NullString `json:"rapporteur"`
	CreatedBy     int32          `json:"created_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Session struct {
	ID               int32        `json:"id"`
	UserID           int32        `json:"user_id"`
	JwtToken         string       `json:"jwt_token"`
	RefreshToken     string       `json:"refresh_token"`
	CreatedAt        sql.NullTime `json:"created_at"`
	ExpiresAt        sql.NullTime `json:"expires_at"`
	RefreshExpiresAt time.Time    `json:"refresh_expires_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
