// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateDelegate(ctx context.Context, arg CreateDelegateParams) (Delegate, error)
	CreateParameter(ctx context.Context, arg CreateParameterParams) (Parameter, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSheet(ctx context.Context, arg CreateSheetParams) (ScoreSheet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDelegate(ctx context.Context, id int32) error
	DeleteParameter(ctx context.Context, id int32) error
	DeleteScore(ctx context.Context, id int32) error
	DeleteSessionByID(ctx context.Context, id int32) error
	DeleteSessionsByUserID(ctx context.Context, userID int32) error
	DeleteSheet(ctx context.Context, id int32) error
	DeleteSheetsByUserID(ctx context.Context, createdBy int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetDelegateByID(ctx context.Context, id int32) (Delegate, error)
	GetDelegateByScoreSheetIDAndName(ctx context.Context, arg GetDelegateByScoreSheetIDAndNameParams) (Delegate, error)
	GetDelegatesByScoreSheetID(ctx context.Context, scoreSheetID int32) ([]Delegate, error)
	GetParameterByID(ctx context.Context, id int32) (Parameter, error)
	GetParameterByScoreSheetIDAndName(ctx context.Context, arg GetParameterByScoreSheetIDAndNameParams) (Parameter, error)
	GetParametersByScoreSheetID(ctx context.Context, scoreSheetID int32) ([]Parameter, error)
	GetScoreByID(ctx context.Context, id int32) (Score, error)
	GetScoresByDelegateID(ctx context.Context, delegateID int32) ([]Score, error)
	GetScoresByParameterID(ctx context.Context, parameterID int32) ([]Score, error)
	GetSessionByID(ctx context.Context, id int32) (Session, error)
	GetSessionsByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID int32) (Session, error)
	GetSheetByID(ctx context.Context, id int32) (ScoreSheet, error)
	GetSheetWithDetailsByID(ctx context.Context, id int32) (GetSheetWithDetailsByIDRow, error)
	GetSheetsByUserID(ctx context.Context, createdBy int32) ([]ScoreSheet, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	TouchScoreSheet(ctx context.Context, id int32) error
	UpdateDelegateName(ctx context.Context, arg UpdateDelegateNameParams) (Delegate, error)
	UpdateParameter(ctx context.Context, arg UpdateParameterParams) (Parameter, error)
	UpdateScore(ctx context.Context, arg UpdateScoreParams) (Score, error)
	UpdateSessionExpiration(ctx context.Context, arg UpdateSessionExpirationParams) (Session, error)
	UpdateSheet(ctx context.Context, arg UpdateSheetParams) (ScoreSheet, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
